### ISSUE TITLE
[BUG] Gres config doesn't translate to the sbatch file

### ISSUE THREAD

**Issue by sean-smith** [NVIDIA/dgxc-benchmarking#5]
**Describe the bug**

When submitting on a Slurm cluster I get the following error:

```
sbatch: error: Cannot find GPU specification, you may not submit a job not requesting GPUs in a GPU partition, partition: ...
sbatch: error: Batch job submission failed: Unspecified error
```

This is because the cluster requires gres specification. When I add in the following to the `cluster_config.yaml` file:

```
launcher:
  llmb_repo: ...
  llmb_install: ...
  gpu_type: ...
environment: {}
slurm:
  account: ...
  gpu_partition: ...
  gpu_gres: 128 # < this
  cpu_partition: cpu
  cpu_gres: null
workloads:
  installed:
  - pretraining_nemotron
  config:
    pretraining_nemotron:
      venv_path: ...
      venv_type: venv
```

It generates a sbatch file but doesn't add anything related to gres there. 

It appears from the code that it's setting `SBATCH_GPUS_PER_NODE` which doesn't seem to do anything.

**Steps/Code to reproduce bug**
Follow [the readme](https://github.com/NVIDIA/dgxc-benchmarking) on a cluster that requires gres. 

**Expected behavior**
Please set the `#SBATCH --gres=gpu:N` in the sbatch file that's generated.

**Additional context**

-----
By submitting this issue, you agree to follow our [code of conduct](https://github.com/NVIDIA/dgxc-benchmarking/blob/main/CODE_OF_CONDUCT.md).
